from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 619)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(11, 11, 771, 511))
        self.graphicsView.setObjectName("graphicsView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 540, 191, 28))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuSimulacion = QtWidgets.QMenu(self.menubar)
        self.menuSimulacion.setObjectName("menuSimulacion")
        self.menuBarab_si_Albert = QtWidgets.QMenu(self.menubar)
        self.menuBarab_si_Albert.setObjectName("menuBarab_si_Albert")
        self.menuErd_s_R_nyi = QtWidgets.QMenu(self.menubar)
        self.menuErd_s_R_nyi.setObjectName("menuErd_s_R_nyi")
        self.menuWatts_y_Strogatz = QtWidgets.QMenu(self.menubar)
        self.menuWatts_y_Strogatz.setObjectName("menuWatts_y_Strogatz")
        self.menuFacebook = QtWidgets.QMenu(self.menubar)
        self.menuFacebook.setObjectName("menuFacebook")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuSimulacion.addSeparator()
        self.menuSimulacion.addSeparator()
        self.menubar.addAction(self.menuSimulacion.menuAction())
        self.menubar.addAction(self.menuBarab_si_Albert.menuAction())
        self.menubar.addAction(self.menuErd_s_R_nyi.menuAction())
        self.menubar.addAction(self.menuWatts_y_Strogatz.menuAction())
        self.menubar.addAction(self.menuFacebook.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "INICIAR SIMULACIÓN"))
        self.menuSimulacion.setTitle(_translate("MainWindow", "Simulacion"))
        self.menuBarab_si_Albert.setTitle(_translate("MainWindow", "Barabási–Albert"))
        self.menuErd_s_R_nyi.setTitle(_translate("MainWindow", "Erdös–Rényi"))
        self.menuWatts_y_Strogatz.setTitle(_translate("MainWindow", "Watts y Strogatz"))
        self.menuFacebook.setTitle(_translate("MainWindow", "Facebook"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
